# Generated by Django 5.1.4 on 2025-04-13 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_verified_customuser_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('face_image', models.ImageField(upload_to='faces/')),
                ('voice_sample', models.FileField(blank=True, null=True, upload_to='voices/')),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_face', models.ImageField(blank=True, null=True, upload_to='matches/faces/')),
                ('uploaded_voice', models.FileField(blank=True, null=True, upload_to='matches/voices/')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('matched_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.person')),
            ],
        ),
    ]
